### ISSUE TITLE
Error on search view

### ISSUE THREAD

**Issue by prasenraj** [shmidt/GooglePlacesSearchController#13]
I am getting this error - fatal error: unexpectedly found nil while unwrapping an Optional value.

when I want to search something then getting this error. how to fix it?

**Comment by ealeksandrov** [comment]
Can't reproduce in 0.1.7 or 0.2.0.
Can you try it in recent release and let me know?

**Comment by prasenraj** [comment]
I fixed this issue and now is working fine. I have changed some code.
