### ISSUE TITLE
Search bar Position

### ISSUE THREAD

**Issue by ErAshu** [shmidt/GooglePlacesSearchController#14]
Hey,
In my project, i have to show search bar below to the navigation bar. How can i modify this. Please suggest.

Thanks!!

**Comment by ShanShafiq01** [comment]
definesPresentationContext = true

**Comment by ErAshu** [comment]
I had done this but not get any success.

**Comment by ealeksandrov** [comment]
This is more UISearchController question, try searching or asking on StackOverflow.
GooglePlacesSearchController is just its subclass, you can use any solutions for UISearchController.
