### ISSUE TITLE
Version 0.2.2 not in CocoaPods

### ISSUE THREAD

**Issue by Tulakshana** [shmidt/GooglePlacesSearchController#26]
It looks like the version 0.2.2 is not pushed to CocoaPods. I'm getting error when trying to install version 0.2.2.

My pod file looks like,
`pod 'GooglePlacesSearchController', '0.2.2'`

My error looks like,
```
[!] CocoaPods could not find compatible versions for pod "GooglePlacesSearchController":
  In Podfile:
    GooglePlacesSearchController (= 0.2.2)

None of your spec sources contain a spec satisfying the dependency: `GooglePlacesSearchController (= 0.2.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

I tried doing `pod repo update` but no luck.

**Comment by ealeksandrov** [comment]
>  🎉  Congrats
> 
 > 🚀  GooglePlacesSearchController (0.2.3) successfully published
>  📅  October 26th, 21:39
>  🌎  https://cocoapods.org/pods/GooglePlacesSearchController
>  👍  Tell your friends!

Version 0.2.3 should be available now.
