### ISSUE TITLE
Release latest version

### ISSUE THREAD

**Issue by ealeksandrov** [shmidt/GooglePlacesSearchController#4]
Thanks for updated fork, can you release latest version and push it to Cocoapods?

**Comment by shmidt** [comment]
Hello,

I recently have a very busy schedule, so I can do that only in a week.
If you want it faster, I added you as collaborator to this repo, so you should have enough control to make it by yourself.

Thanks for your interest and have a great weekend!

**Comment by ealeksandrov** [comment]
Thanks, will do a small update.
